-   id: checkstyle-java
    name: Checkstyle for Java
    description: Runs the necessary checkstyle checks on java code
    entry: ./check-code.sh
    language: script
    files: \.java$ # We don't technically need this, as the script will filter for us, but this will allow the hook to be skipped if no Java is changed.

